'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const domain = require('../domain/hakedisWorkflow');
const providers = require('../domain/hakedisProviders');
const input = { projectReference: 'BUILD-42', periodStart: '2026-07-01', periodEnd: '2026-07-31', claimedCents: 10000, retentionBps: 1000, currency: 'TRY', lineItems: [{ code: 'FOUNDATION', amountCents: 6000 }, { code: 'STEEL', amountCents: 4000 }], evidence: [{ uri: 'vault://measurements/1', sha256: 'a'.repeat(64) }] };

test('validates exact claim totals, retention and evidence', () => { const claim = domain.validateClaim(input); assert.equal(claim.payableCents, 9000); assert.throws(() => domain.validateClaim({ ...input, claimedCents: 9999 }), /equal/); assert.throws(() => domain.validateClaim({ ...input, retentionBps: 10001 }), /0-10000/); });
test('rejects invalid periods, unsafe evidence and fractional money', () => { assert.throws(() => domain.validateClaim({ ...input, periodStart: '2026-08-01' }), /period/); assert.throws(() => domain.validateClaim({ ...input, evidence: [{ uri: 'file:///tmp/a', sha256: 'a'.repeat(64) }] }), /evidence/); assert.throws(() => domain.validateClaim({ ...input, claimedCents: 1.2, lineItems: [{ code: 'x', amountCents: 1.2 }] }), /safe integer/); });
test('enforces deterministic state, roles and independent approvals', () => { const owner = { id: 'owner', role: 'enterprise_partner' }; const verifier = { id: 'verify', role: 'solution_architect' }; const submitted = domain.applyCommand({ state: 'draft', version: 1, ownerId: 'owner' }, owner, 'submit'); assert.equal(submitted.state, 'measurement_review'); const approval = { kind: 'measurement', decision: 'approved', requestedBy: 'owner', decidedBy: 'verify' }; assert.equal(domain.applyCommand(submitted, verifier, 'approve_measurement', {}, approval).state, 'finance_review'); assert.throws(() => domain.applyCommand(submitted, verifier, 'approve_measurement', {}, { ...approval, decidedBy: 'owner' }), /independent/); });
test('tenant and participant scope fail closed', () => { const claim = { tenantId: 't1', ownerId: 'owner', participantIds: ['participant'] }; assert.equal(domain.authorizeScope({ tenantId: 't1', id: 'participant', role: 'viewer' }, claim), true); assert.throws(() => domain.authorizeScope({ tenantId: 't2', id: 'owner', role: 'admin' }, claim), /cross-tenant/); assert.throws(() => domain.authorizeScope({ tenantId: 't1', id: 'other', role: 'viewer' }, claim), /outside/); });
test('delivery retry is bounded and terminal failures dead-letter', () => { assert.equal(domain.nextDelivery(0, true).status, 'retry'); assert.equal(domain.nextDelivery(0, false).status, 'dead_letter'); assert.equal(domain.nextDelivery(4, true).status, 'dead_letter'); });
test('typed provider binds idempotency and receipt hash', async () => { process.env.HAKEDIS_PAYMENT_PROVIDER_URL = 'https://pay.example.test/v1'; process.env.HAKEDIS_PAYMENT_PROVIDER_TOKEN = 'token'; let captured; const receipt = await providers.dispatch({ connector: 'payment', operation: 'payout.create', idempotencyKey: 'payment-key-1', payload: { payloadHash: 'b'.repeat(64) }, fetchImpl: async (_url, options) => { captured = options; return { ok: true, json: async () => ({ id: 'pay-1', payloadHash: 'b'.repeat(64) }) }; } }); assert.equal(receipt.id, 'pay-1'); assert.equal(captured.headers['idempotency-key'], 'payment-key-1'); delete process.env.HAKEDIS_PAYMENT_PROVIDER_URL; delete process.env.HAKEDIS_PAYMENT_PROVIDER_TOKEN; });
test('provider rejects generic, insecure and mismatched operations', async () => { await assert.rejects(() => providers.dispatch({ connector: 'generic', operation: 'anything', idempotencyKey: 'provider-key-2', payload: {} }), /unsupported/); process.env.HAKEDIS_PAYMENT_PROVIDER_URL = 'http://pay.example.test'; process.env.HAKEDIS_PAYMENT_PROVIDER_TOKEN = 'token'; await assert.rejects(() => providers.dispatch({ connector: 'payment', operation: 'payout.create', idempotencyKey: 'provider-key-3', payload: {} }), /HTTPS/); delete process.env.HAKEDIS_PAYMENT_PROVIDER_URL; delete process.env.HAKEDIS_PAYMENT_PROVIDER_TOKEN; });
test('migration owns claims, one-use approvals, receipts and immutable audit', () => { const sql = fs.readFileSync(path.join(__dirname, '../db/migration_012_governed_hakedis.sql'), 'utf8'); for (const term of ['hakedis_memberships', 'hakedis_claims', 'hakedis_one_pending_approval_idx', 'consumed_at', 'hakedis_claim_events', 'hakedis_delivery_jobs', 'hakedis_provider_receipts', 'append-only']) assert.match(sql, new RegExp(term)); assert.doesNotMatch(sql, /DROP TABLE|TRUNCATE/i); });
test('server exposes only governed API and launcher is non-destructive', () => { const server = fs.readFileSync(path.join(__dirname, '../server.js'), 'utf8'); const launcher = fs.readFileSync(path.join(__dirname, '../../start.sh'), 'utf8'); const scripts = JSON.parse(fs.readFileSync(path.join(__dirname, '../package.json'), 'utf8')).scripts; assert.match(server, /api\/v1\/hakedis/); assert.match(server, /status\(410\)/); assert.doesNotMatch(server, /routes\/(ai|batch09GapAi|customViews|customFeatures)/); for (const mode of ['check)', 'migrate)', 'start)']) assert.match(launcher, new RegExp(mode.replace(')', '\\)'))); assert.doesNotMatch(`${launcher}\n${JSON.stringify(scripts)}`, /kill\s+-9|DROP DATABASE|createdb|brew services|npm install|seed\.sql|db:reset|alliance_pass/); });
